{"name": "Login with invalid parameters", "status": "broken", "statusDetails": {"message": "AttributeError: 'Context' object has no attribute 'allure'\n", "trace": "  File \"C:\\Users\\USER\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\USER\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\loginSteps.py\", line 100, in step_impl\n    context.allure.attach(context.driver.get_screenshot_as_png(), name=\"User must succesfully login to the Dashboard page\", attachment_type=AttachmentType.PNG)\n    ^^^^^^^^^^^^^^\n  File \"C:\\Users\\USER\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n"}, "steps": [{"name": "Given I Launch the browser", "status": "passed", "start": 1710977274295, "stop": 1710977278286}, {"name": "When I open orange HRM LoginPage", "status": "passed", "start": 1710977278286, "stop": 1710977279331}, {"name": "And Enter wrong password username \"admin\" and password \"admin\"", "status": "passed", "start": 1710977279331, "stop": 1710977279401}, {"name": "And Click on login button", "status": "passed", "start": 1710977279401, "stop": 1710977280461}, {"name": "Then Show message the Invalid credentials", "status": "broken", "statusDetails": {"message": "AttributeError: 'Context' object has no attribute 'allure'\n", "trace": "  File \"C:\\Users\\USER\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\USER\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\loginSteps.py\", line 100, in step_impl\n    context.allure.attach(context.driver.get_screenshot_as_png(), name=\"User must succesfully login to the Dashboard page\", attachment_type=AttachmentType.PNG)\n    ^^^^^^^^^^^^^^\n  File \"C:\\Users\\USER\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n"}, "start": 1710977280461, "stop": 1710977280991}], "start": 1710977274294, "stop": 1710977280991, "uuid": "009a1d8c-6e46-4ed5-ab16-a5531ac3082b", "historyId": "d5e8681c802ec665563eb1960aa07645", "fullName": ": Login with invalid parameters", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}